import { Headset, PhoneCall, Radio, Waveform } from '@phosphor-icons/react'
import { useState } from 'react'
import { useTenant } from '../../app/TenantProvider'
import { Badge } from '../../components/ui/Badge'

export function LiveCallsPage() {
  const { tenantId, repository } = useTenant()
  const calls = repository.getCalls(tenantId)
  const [selectedId, setSelectedId] = useState(calls[0]?.id)
  const selected = calls.find((item) => item.id === selectedId) ?? calls[0]
  return <><header className="page-heading"><div><div className="eyebrow">Live operations</div><h1>Live calls</h1><p>Observe active reminder conversations and handoff readiness.</p></div><Badge>{calls.filter((item) => ['Calling', 'Connected'].includes(item.status)).length} live</Badge></header><section className="panel calls-layout"><aside className="call-sidebar"><div className="call-sidebar-header"><strong>Current and recent</strong><div className="row-meta">Synthetic activity</div></div>{calls.map((item) => <button className={`call-row ${item.id === selected?.id ? 'selected' : ''}`} key={item.id} onClick={() => setSelectedId(item.id)}><span className="avatar">{item.initials}</span><span><span className="row-title">{item.patientName}</span><span className="row-meta">{item.intent} · {item.duration}</span></span><Badge>{item.status}</Badge></button>)}</aside>{selected && <div className="call-detail"><header className="call-detail-header"><div className="call-identity"><span className="avatar">{selected.initials}</span><div><h2>{selected.patientName}</h2><div className="subtle">{selected.phone} · {selected.appointment}</div></div></div><Badge>{selected.status}</Badge></header><div className="call-status-grid"><div className="call-status-item"><span>Detected intent</span><strong>{selected.intent}</strong></div><div className="call-status-item"><span>Call duration</span><strong>{selected.duration}</strong></div><div className="call-status-item"><span>Connection</span><strong>{selected.connection}</strong></div></div><section><div className="panel-header" style={{ paddingInline: 0 }}><div><h2>Conversation</h2><div className="subtle">Live transcript · {selected.language}</div></div><Waveform size={23} color="var(--cyan-600)" /></div><div className="transcript">{selected.transcript.map((line, index) => <div className={`transcript-line ${line.speaker === 'Patient' ? 'patient' : ''}`} key={index}><strong>{line.speaker}</strong>{line.text}</div>)}</div></section><div style={{ display: 'flex', gap: 10, marginTop: 26 }}><button className="button button-primary"><Headset size={18} />Prepare warm transfer</button><button className="button button-secondary"><PhoneCall size={18} />Call controls</button></div><div className="row-meta" style={{ marginTop: 12 }}><Radio size={13} /> Demo stream · no real call is active</div></div>}</section></>
}
